# Generated by Django 3.0.3 on 2020-05-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_user',
        ),
    ]
