# Generated by Django 3.0.3 on 2020-05-18 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing_app', '0002_remove_userprofile_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_user',
            field=models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
