# Generated by Django 3.0.3 on 2020-09-29 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0002_auto_20200929_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
