# Generated by Django 3.0.3 on 2021-01-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0003_auto_20200929_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
        ),
    ]
