# Generated by Django 3.0.3 on 2020-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0003_userprofile_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_ads',
            field=models.CharField(choices=[('premium', 'Premium'), ('vip', 'VIP'), ('regular', 'Regular')], default='Regular', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='car_promoted',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_seller',
            field=models.CharField(choices=[('dealer', 'Dealer'), ('private', 'Private')], default='Dealer', max_length=100),
        ),
    ]
