# Generated by Django 3.0.3 on 2020-05-24 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing_app', '0004_auto_20200518_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_user',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
