# Generated by Django 3.0.3 on 2020-06-23 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing_app', '0005_auto_20200524_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
